jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: xvfb-run npx playwright test
